### PR TITLE
Update to support svg.js v3.x and add type definitions

### PR DESCRIPTION
**Pull request by plungingChode**
I created this update based on the updated [svg.draggable.js](https://github.com/svgdotjs/svg.draggable.js) and the discussion in PR #48.

### CODE REVIEW

**Comment by hippogrammer** [comment]
this would be very nice to have!!

**Comment by Fuzzyma** [comment]
I am swamped with work atm so I currently have no chance to check this PR.
For everyone who needs this, they can install this branch directly via npm and use it that way

**Comment by hippogrammer** [comment]
can you add the dist/ folder so we can use it in our node modules? Please @plungingChode :)

**Comment by Fuzzyma** [comment]
@hippogrammer dist folder is not commited to git. Only the source files are. But You can just build it yourself locally

**Comment by plungingChode** [comment]
@hippogrammer Also, I forgot to add it to the readme, but this is how you would use it from node modules (as ES6 modules)

```js
import { SVG } from '@svgdotjs/svg.js'
import '@svgdotjs/svg.draw.js'
```

**Comment by hippogrammer** [comment]
Gotcha, its just i installed directly from this branch and i had to build manually in order for it to work. Also saw that dist was committed in the original svg.draw.js. thanks for the help everyone!

**Comment by PooLP** [comment]
Please, release it officially.
Thanks

**Comment by jonybekov** [comment]
@Fuzzyma Are you still busy to review this PR?

**Comment by AlexeyPlodenko** [comment]
@plungingChode thank you for your effort.
Can you please publish your package to npmjs.com?

In the mean time, I have publish a fork of your code at https://www.npmjs.com/package/svgdotjs-svg3.draw.js
Ping me once you publish, and I will remove mine.
Thank you.

**Comment by Fuzzyma** [comment]
@jonybekov sorry obviously I forgot about this. I am traveling right now and back in a month so it might still a whole. Feel free to ping me again!

**Comment by Fuzzyma** [comment]
@plungingChode thanks for your contribution. Nice work!
I saw that you added yourself to the contributors in the package.json. Are you planning on helping to maintain this plugin in the longterm? :P

**Comment by Fuzzyma** [comment]
This is now published under `@svgdotjs/svg.draw.js`

**Comment by plungingChode** [comment]
@Fuzzyma My bad about the contributors list, this was over 3 years ago and I had no idea what that actually entailed. Feel free to remove me from there, since I don't think I'll be able to help out much.

**Comment by Fuzzyma** [comment]
No worries 😄. I wasn't really serious :).
Thanks for implementing this whole thing. I basically took it as is :)

**Pull request merged**
